export const GameSignals = {
    PLAYER_FIRED: 'PLAYER_FIRED',
    ENEMY_FIRED: 'ENEMY_FIRED',
    ENEMY_DIED: 'ENEMY_DIED',
    PLAYER_DIED: 'PLAYER_DIED',
    RUN_RESTARTED: 'RUN_RESTARTED',
    BUFF_COLLECTED: 'BUFF_COLLECTED',
    EXPLOSION_TRIGGERED: 'EXPLOSION_TRIGGERED',
};
