export type GameConfig = {
    godMode: boolean;
    playerSpeed: number;
    enemySpeed: number;
    enemySineOscillationSpeed: number;
    enemySineOscillationAmplitude: number;
    enemyChaseSpeed: number;
    armoredEnemyHealth: number;
    enemySpawnInterval: number;
    enemyMinimumSpawnInterval: number;
    enemySpawnIntervalDecreasePerSecond: number;
    enemySpeedIncreasePerSecond: number;
    enemyMaximumSpeedIncrease: number;
    projectileSpeed: number;
    fireCooldown: number;
    collisionDistance: number;
    backgroundSpeed: number;
    particleCountPerExplosion: number;
    particleMinLifetime: number;
    particleMaxLifetime: number;
    particleMinSpeed: number;
    particleMaxSpeed: number;
    buffDropChance: number;
    buffFallSpeed: number;
    buffMagnetRadius: number;
    buffMagnetSpeed: number;
    enemyProjectileSpeed: number;
    enemyShootingRange: number;
    enemyFireCooldown: number;
    rapidFireCooldown: number;
    rapidFireDuration: number;
};

export const gameConfig: GameConfig = {
    godMode: true,
    playerSpeed: 6,
    enemySpeed: 4,
    enemySineOscillationSpeed: 0.1,
    enemySineOscillationAmplitude: 10,
    enemyChaseSpeed: 1.5,
    armoredEnemyHealth: 3,
    enemySpawnInterval: 100,
    enemyMinimumSpawnInterval: 35,
    enemySpawnIntervalDecreasePerSecond: 1.5,
    enemySpeedIncreasePerSecond: 0.02,
    enemyMaximumSpeedIncrease: 0.75,
    projectileSpeed: 12,
    fireCooldown: 10,
    collisionDistance: 25,
    backgroundSpeed: 3,
    particleCountPerExplosion: 15,
    particleMinLifetime: 15,
    particleMaxLifetime: 35,
    particleMinSpeed: 1.5,
    particleMaxSpeed: 5,
    buffDropChance: 0.12,
    buffFallSpeed: 2.5,
    buffMagnetRadius: 400,
    buffMagnetSpeed: 10,
    enemyProjectileSpeed: 8,
    enemyShootingRange: 620,
    enemyFireCooldown: 80,
    rapidFireCooldown: 4,
    rapidFireDuration: 360,
};
