export const GameSignals = {
    PLAYER_FIRED: 'PLAYER_FIRED',
    ENEMY_FIRED: 'ENEMY_FIRED',
    ENEMY_DIED: 'ENEMY_DIED',

    PLAYER_DIED: 'PLAYER_DIED',
    PLAYER_MOVED: 'PLAYER_MOVED',

    RUN_RESTARTED: 'RUN_RESTARTED',
    BUFF_COLLECTED: 'BUFF_COLLECTED',
    EXPLOSION_TRIGGERED: 'EXPLOSION_TRIGGERED',

    WEAPON_PICKED_UP: 'WEAPON_PICKED_UP',
    WEAPON_EQUIPPED: 'WEAPON_EQUIPPED',

    PLASMA_BEAM_ACTIVE: 'PLASMA_BEAM_ACTIVE',
};
